# Generated by Django 6.0.3 on 2026-03-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Demand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=100)),
                (
                    "specification",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("quantity", models.CharField(blank=True, max_length=50, null=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("origin", models.CharField(blank=True, max_length=200, null=True)),
                ("price", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("update_time", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=100)),
                (
                    "specification",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("quantity", models.CharField(blank=True, max_length=50, null=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("origin", models.CharField(blank=True, max_length=200, null=True)),
                ("price", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("update_time", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="product",
            name="medicine",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
