# Generated by Django 6.0.3 on 2026-03-27 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0003_acupuncturepoint_image"),
        ("sales", "0003_demand_created_at_demand_user_supply_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supply",
            name="medicine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="medicine.medicine",
            ),
        ),
    ]
