# Generated by Django 6.0.3 on 2026-03-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_supply_medicine"),
    ]

    operations = [
        migrations.AddField(
            model_name="supply",
            name="invoice_requirement",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="supply",
            name="minimum_order",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="supply",
            name="packaging",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="supply",
            name="payment",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="supply",
            name="qualification_requirement",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="supply",
            name="quality_requirement",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="supply",
            name="sample",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
