# Generated by Django 6.0.3 on 2026-03-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_supply_invoice_requirement_supply_minimum_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supply",
            name="angui_price",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="supply",
            name="bozhou_price",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="supply",
            name="chengdu_price",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="supply",
            name="lianqiao_price",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="supply",
            name="puning_price",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="supply",
            name="yulin_price",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
