# Generated by Django 6.0.3 on 2026-03-30 03:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_supply_angui_price_supply_bozhou_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=100)),
                (
                    "specification",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("origin", models.CharField(blank=True, max_length=200, null=True)),
                ("price", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "bozhou_price",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("angui_price", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "chengdu_price",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("yulin_price", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "lianqiao_price",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "puning_price",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "supply",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_histories",
                        to="sales.supply",
                    ),
                ),
            ],
        ),
    ]
