# Generated by Django 6.0.3 on 2026-03-31 07:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0004_alter_acupuncturepoint_options_and_more"),
        ("sales", "0007_pricehistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="demand",
            options={"verbose_name": "求购信息", "verbose_name_plural": "求购信息"},
        ),
        migrations.AlterModelOptions(
            name="pricehistory",
            options={
                "ordering": ["-date", "medicine_name", "location"],
                "verbose_name": "价格历史",
                "verbose_name_plural": "价格历史",
            },
        ),
        migrations.AlterModelOptions(
            name="supply",
            options={"verbose_name": "供应信息", "verbose_name_plural": "供应信息"},
        ),
        migrations.AlterUniqueTogether(
            name="pricehistory",
            unique_together={("medicine_name", "specification", "location", "date")},
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="location",
            field=models.CharField(default="亳州", max_length=50, verbose_name="市场"),
        ),
        migrations.AlterField(
            model_name="demand",
            name="contact_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="联系人"
            ),
        ),
        migrations.AlterField(
            model_name="demand",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="联系电话"
            ),
        ),
        migrations.AlterField(
            model_name="demand",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="demand",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="demand",
            name="location",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="地区"
            ),
        ),
        migrations.AlterField(
            model_name="demand",
            name="medicine_name",
            field=models.CharField(max_length=100, verbose_name="药材名称"),
        ),
        migrations.AlterField(
            model_name="demand",
            name="origin",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="产地要求"
            ),
        ),
        migrations.AlterField(
            model_name="demand",
            name="price",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="价格"
            ),
        ),
        migrations.AlterField(
            model_name="demand",
            name="quantity",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="求购数量"
            ),
        ),
        migrations.AlterField(
            model_name="demand",
            name="specification",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="规格"
            ),
        ),
        migrations.AlterField(
            model_name="demand",
            name="update_time",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="更新时间"
            ),
        ),
        migrations.AlterField(
            model_name="demand",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="日期"
            ),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="medicine_name",
            field=models.CharField(max_length=100, verbose_name="药材名称"),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="价格"
            ),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="specification",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="规格"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="angui_price",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="安国价格"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="bozhou_price",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="亳州价格"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="chengdu_price",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="成都价格"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="contact_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="联系人"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="联系电话"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="supply",
            name="invoice_requirement",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="票据需求"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="lianqiao_price",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="廉桥价格"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="location",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="药材库存"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="medicine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="medicine.medicine",
                verbose_name="中药材",
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="medicine_name",
            field=models.CharField(max_length=100, verbose_name="药材名称"),
        ),
        migrations.AlterField(
            model_name="supply",
            name="minimum_order",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="起售量"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="origin",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="药材产地"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="packaging",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="包装"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="payment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="付款"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="price",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="售价"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="puning_price",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="普宁价格"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="qualification_requirement",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="资质要求"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="quality_requirement",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="质量需求"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="quantity",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="供应数量"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="sample",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="寄样"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="specification",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="规格"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="update_time",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="更新时间"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="yulin_price",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="玉林价格"
            ),
        ),
        migrations.RemoveField(
            model_name="pricehistory",
            name="angui_price",
        ),
        migrations.RemoveField(
            model_name="pricehistory",
            name="bozhou_price",
        ),
        migrations.RemoveField(
            model_name="pricehistory",
            name="chengdu_price",
        ),
        migrations.RemoveField(
            model_name="pricehistory",
            name="lianqiao_price",
        ),
        migrations.RemoveField(
            model_name="pricehistory",
            name="origin",
        ),
        migrations.RemoveField(
            model_name="pricehistory",
            name="puning_price",
        ),
        migrations.RemoveField(
            model_name="pricehistory",
            name="supply",
        ),
        migrations.RemoveField(
            model_name="pricehistory",
            name="yulin_price",
        ),
    ]
