# Generated by Django 6.0.3 on 2026-03-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_alter_demand_options_alter_pricehistory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricehistory",
            options={"verbose_name": "价格历史", "verbose_name_plural": "价格历史"},
        ),
        migrations.AlterUniqueTogether(
            name="pricehistory",
            unique_together={("medicine_name", "specification", "origin", "date")},
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="angui_price",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="安国价格"
            ),
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="bozhou_price",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="亳州价格"
            ),
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="chengdu_price",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="成都价格"
            ),
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="lianqiao_price",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="廉桥价格"
            ),
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="origin",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="产地"
            ),
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="puning_price",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="普宁价格"
            ),
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="yulin_price",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="玉林价格"
            ),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="date",
            field=models.DateField(verbose_name="日期"),
        ),
        migrations.RemoveField(
            model_name="pricehistory",
            name="location",
        ),
        migrations.RemoveField(
            model_name="pricehistory",
            name="price",
        ),
    ]
