# Generated by Django 6.0.3 on 2026-03-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcupuncturePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("location", models.TextField(blank=True, null=True)),
                ("functions", models.TextField(blank=True, null=True)),
                ("indications", models.TextField(blank=True, null=True)),
                ("acupuncture_method", models.TextField(blank=True, null=True)),
                ("precautions", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DietaryTherapy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("ingredients", models.TextField()),
                ("preparation", models.TextField(blank=True, null=True)),
                ("functions", models.TextField(blank=True, null=True)),
                ("indications", models.TextField(blank=True, null=True)),
                ("precautions", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("latin_name", models.CharField(blank=True, max_length=200, null=True)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("origin", models.CharField(blank=True, max_length=100, null=True)),
                ("properties", models.TextField(blank=True, null=True)),
                ("functions", models.TextField(blank=True, null=True)),
                ("indications", models.TextField(blank=True, null=True)),
                ("usage", models.TextField(blank=True, null=True)),
                ("precautions", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="medicine_images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("ingredients", models.TextField()),
                ("dosage", models.TextField(blank=True, null=True)),
                ("preparation", models.TextField(blank=True, null=True)),
                ("functions", models.TextField(blank=True, null=True)),
                ("indications", models.TextField(blank=True, null=True)),
                ("precautions", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
