# Generated by Django 6.0.3 on 2026-03-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietarytherapy",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="prescription",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
