# Generated by Django 6.0.3 on 2026-03-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0002_dietarytherapy_image_prescription_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="acupuncturepoint",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
