# Generated by Django 6.0.3 on 2026-03-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0003_acupuncturepoint_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acupuncturepoint",
            options={"verbose_name": "针灸穴位", "verbose_name_plural": "针灸穴位"},
        ),
        migrations.AlterModelOptions(
            name="dietarytherapy",
            options={"verbose_name": "药膳食疗", "verbose_name_plural": "药膳食疗"},
        ),
        migrations.AlterModelOptions(
            name="medicine",
            options={"verbose_name": "中药材", "verbose_name_plural": "中药材"},
        ),
        migrations.AlterModelOptions(
            name="prescription",
            options={"verbose_name": "方剂", "verbose_name_plural": "方剂"},
        ),
        migrations.AlterField(
            model_name="acupuncturepoint",
            name="acupuncture_method",
            field=models.TextField(blank=True, null=True, verbose_name="刺灸法"),
        ),
        migrations.AlterField(
            model_name="acupuncturepoint",
            name="functions",
            field=models.TextField(blank=True, null=True, verbose_name="功效"),
        ),
        migrations.AlterField(
            model_name="acupuncturepoint",
            name="image",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="图片"
            ),
        ),
        migrations.AlterField(
            model_name="acupuncturepoint",
            name="indications",
            field=models.TextField(blank=True, null=True, verbose_name="主治"),
        ),
        migrations.AlterField(
            model_name="acupuncturepoint",
            name="location",
            field=models.TextField(blank=True, null=True, verbose_name="定位"),
        ),
        migrations.AlterField(
            model_name="acupuncturepoint",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="acupuncturepoint",
            name="precautions",
            field=models.TextField(blank=True, null=True, verbose_name="注意事项"),
        ),
        migrations.AlterField(
            model_name="dietarytherapy",
            name="functions",
            field=models.TextField(blank=True, null=True, verbose_name="功效"),
        ),
        migrations.AlterField(
            model_name="dietarytherapy",
            name="image",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="图片"
            ),
        ),
        migrations.AlterField(
            model_name="dietarytherapy",
            name="indications",
            field=models.TextField(blank=True, null=True, verbose_name="适用症"),
        ),
        migrations.AlterField(
            model_name="dietarytherapy",
            name="ingredients",
            field=models.TextField(verbose_name="原料"),
        ),
        migrations.AlterField(
            model_name="dietarytherapy",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="dietarytherapy",
            name="precautions",
            field=models.TextField(blank=True, null=True, verbose_name="注意事项"),
        ),
        migrations.AlterField(
            model_name="dietarytherapy",
            name="preparation",
            field=models.TextField(blank=True, null=True, verbose_name="制法"),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="category",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="分类"
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="functions",
            field=models.TextField(blank=True, null=True, verbose_name="功效"),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="image",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="图片"
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="indications",
            field=models.TextField(blank=True, null=True, verbose_name="主治"),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="latin_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="拉丁名"
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="origin",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="产地"
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="precautions",
            field=models.TextField(blank=True, null=True, verbose_name="注意事项"),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="properties",
            field=models.TextField(blank=True, null=True, verbose_name="性味归经"),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="usage",
            field=models.TextField(blank=True, null=True, verbose_name="用法用量"),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="dosage",
            field=models.TextField(blank=True, null=True, verbose_name="用量"),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="functions",
            field=models.TextField(blank=True, null=True, verbose_name="功效"),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="image",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="图片"
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="indications",
            field=models.TextField(blank=True, null=True, verbose_name="主治"),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="ingredients",
            field=models.TextField(verbose_name="组成"),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="precautions",
            field=models.TextField(blank=True, null=True, verbose_name="注意事项"),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="preparation",
            field=models.TextField(blank=True, null=True, verbose_name="制法"),
        ),
    ]
